services:
  keykit:
    build: .
    container_name: keykit
    image: keykit:beta
    privileged: true
    environment:
      - XDG_RUNTIME_DIR=/tmp
    volumes:
      - /dev/snd:/dev/snd/ 
      - ./samples/Phonk_/Kicks/Kick (1).wav:/samples/b
      - ./samples/Phonk_/Snares/PHONKIN SNARE 1.wav:/samples/a
      - /run/user/1000/pipewire-0:/tmp/pipewire-0
    cap_add:
      - SYS_NICE

